[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.lints.clippy]
nursery = "warn"
pedantic = "warn"

default_trait_access = { level = "allow", priority = 1 }
missing_errors_doc = { level = "allow", priority = 1 }
missing_panics_doc = { level = "allow", priority = 1 }
ref_option = { level = "allow", priority = 1 }

absolute_paths = "warn"

[workspace.dependencies]
fretwire_format = { path = "./crates/fretwire_format/" }
fretwire_locale = { path = "./crates/fretwire_locale/" }

arbtest = "0.3.2"
