[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.lints.clippy]
default_trait_access = { level = "allow", priority = 1 }
missing_errors_doc = { level = "allow", priority = 1 }
nursery = "warn"
pedantic = "warn"

[workspace.dependencies]
fretwire_format = { path = "./crates/fretwire_format/" }
fretwire_locale = { path = "./crates/fretwire_locale/" }

arbtest = "0.3.2"
