[package]
name = "fretwire_locale"
version.workspace = true
edition.workspace = true

[lib]
doctest = false

[dependencies]
icu_calendar = "2.3.0"
icu_casemap = "2.3.0"
icu_collator = "2.3.0"
icu_datetime = "2.3.0"
icu_locale = "2.3.0"
icu_properties = "2.3.0"
icu_time = "2.3.0"
jiff = "0.2.37"
jiff-icu = "0.2.2"
writeable = "0.6.3"

[lints]
workspace = true
